### ISSUE TITLE
Does PPMParam need to be defined at all?

### ISSUE THREAD

**Issue by ekr** [abetterinternet/ppm-specification#104]
The current specification describes a PPMParam struct and defines a TaskID as SHA-256(PPMParam). However, because the PPMParam is never rendered on the wire. Rather it is just serialized in order to be fed into SHA-256. The parameters are provided to the endpoints out of band.

Consider a client implementor who behaves as follows:

- Create a JSON structure J that defines the parameters.
- Translate J into PPAParam P.
- Send the client the pair [J, TaskID = SHA-256(P)]

You'll note that the client never sees the PPAParam at all. As far as I can tell, this would be a completely conformant implementation. Similar comments apply to the aggregators as we also do not define how *they* are configured. So, similarly they could just be sent JSON and have a TaskID -> JSON lookup table. This isn't just a possible implementation, but it's likely to be a common one, because people have whatever central configuration system they have and don't necessarily want to carry around some binary blob.

In fact, the only reason people need to see the PPAParam structure at all as opposed to the information in it is to hash it to create TaskID (yes, i appreciate that I suggested the hashing thing).

So what I suggest is we merely make a list of the things that the client and the aggregators need to know respectively and not define any structure that contains that list. Then we can just pick the TaskID randomly.

When we originally discussed hashing, the idea was to have parameters be transitively incorporated into the protocol to avoid situations where each side is using different parameters. It's not clear to me that this is that important. A malicious client can just lie and use its own parameters, and if there is a bug, then it's just as likely it involves misinterpreting the parameters.

**Comment by tgeoghegan** [comment]
I think our goal was to force clients to commit to a set of PPMParams, but you're right, nothing really ties the actual behavior of clients or aggregators to the PPMParams. We put a 16 byte nonce into PPMParam with the intention of guaranteeing that PPMTaskID would be unique, but I think we can just instead have PPMTaskID be that nonce. As for the sizes, we picked len(PPMTaskID) = 32 to match the length of a SHA-256, and len(PPMParam.nonce) == 16 to match a v4 UUID. If PPMTaskID is going to be randomly generated instead of derived, then 16 bytes should suffice.

**Comment by cjpatton** [comment]
> So what I suggest is we merely make a list of the things that the client and the aggregators need to know respectively and not define any structure that contains that list. Then we can just pick the TaskID randomly.
> 
> When we originally discussed hashing, the idea was to have parameters be transitively incorporated into the protocol to avoid situations where each side is using different parameters. It's not clear to me that this is that important. A malicious client can just lie and use its own parameters, and if there is a bug, then it's just as likely it involves misinterpreting the parameters.

The problem we're trying to solve by binding the PPM params to encryption has less to do with malicious clients than honest ones. Namely, it's meant to ensure that honest aggregators reject reports that were generated with incorrect parameters.

As to whether this binding is strictly necessary, I agree that it's not clear that there's an attack it prevents right now. This binding is conservative in the sense that it aims to mitigate attacks that may come up in the future, as the set of parameters evolve.

Another benefit of this binding is that it ensures the client knows what privacy-sensitive parameters are enforced by honest aggreagators. Namely, the batch size, minimum batch window, and, eventually, parameters for DP.

To conclude, there may not be a need to define a serialization format for PPM params, and it would be fine to just randomly the task ID. However, there should be some sort of binding between the params and HPKE encryption.

**Comment by ekr** [comment]
You seem to be assuming a very specific implementation, but nothing in the spec requires that, as shown by my example above.

**Comment by tgeoghegan** [comment]
Based on our conversation in the call on 8/18, I think the consensus is

- we should not define `struct Param` but instead informally list the parameters that all participants must agree on
- `task_id` (which does appear in several on-the-wire messages) will become a randomly generated sequence of bytes instead of being a SHA-256 of the `Param`

Unless someone objects (tagging @chris-wood to make sure he sees this issue as he hasn't participated yet) I'm going to make this doc change this week, after landing #135.

**Comment by chris-wood** [comment]
#135 seems like it complicates this, since we'd have to spell out some way to sort aggregators. Do we want to land this change before than one?

**Comment by tgeoghegan** [comment]
I want to land #135 first, since it's just about done. I don't think it'll be too hard to change references to `Param.aggregators` into references to an ordered list of aggregators.

**Comment by chris-wood** [comment]
Sounds good!
