### ISSUE TITLE
Do something about long-running requests

### ISSUE THREAD

**Issue by ekr** [abetterinternet/ppm-specification#111]
It's easy to imagine that a request will take a long time, especially if you are using Collect and that has to trigger a bunch of work from the leader. We need some way of handling this.

**Comment by tgeoghegan** [comment]
This intersects with something we were discussing last week, which is whether or not `struct PPMParam` should have `HpkeConfig collector_config` in it, or a URL from which collector config can be fetched dynamically. We decided on the former to spare collectors of running an online HTTP server. However, if we adopt an asynchronous model for collect requests, then we might need collectors to be an HTTP server anyway so that the leader can notify them that a collect request is complete, in which case we should make collectors have a `key_config` endpoint like the other servers.

**Comment by tgeoghegan** [comment]
@cjpatton and I were talking about this today. We agree that `CollectReq`/`CollectResp` definitely needs to be made asynchronous since in the `poplar1` case, servicing a `CollectReq` will definitely incur lots of expensive work between the aggregators (this is less likely in the `prio3` case because the aggregators aren't blocked on obtaining the aggregation parameter from the collector in that VDAF).

What I'm not sure if is whether we should make all the interactions between the aggregators during preparation and verification asynchronous, and I'm not sure how to decide. It seems like it should be possible for leaders to scope each aggregate requests to a small enough number of shares that each one can reasonably be serviced synchronously.

**Comment by cjpatton** [comment]
For collect requests, I'd also note here that asynchronicity is probably going to be important for `prio3`, as it's possible that the aggregation flow will fall behind the upload flow. (Imagine the helper can only handle 1000 reports/sec, but the clients are uploading 1million reports/sec.)

As for aggregate requests, I would expect these to be able to be completed fairly quickly (in a matter of seconds, in the worst case). Based on our experience so far, the most expensive part appears to be interacting with long-term storage, which is required for anti-replay and, if we take #174, looking up report shares. I think we can hold off on making these requests asynchronous until we've gotten enough deployment experience to determine if this is going to be a problem.

**Comment by tgeoghegan** [comment]
@martinthomson provided some interesting prior art that we should rely on when addressing this: https://mailarchive.ietf.org/arch/msg/ppm/dNf3eA-r6qGgeBZ9PhnHjJ1pSEc/
