### ISSUE TITLE
Consider making the Leader a non-aggregator

### ISSUE THREAD

**Issue by eriktaubeneck** [abetterinternet/ppm-specification#166]
In section 2.1: "The leader is responsible for coordinating the protocol. It receives the encrypted shares, distributes them to the helpers, and orchestrates the process of computing the final measurement as requested by the collector."

Then, in section 6.1.3: "The leader is also an aggregator, and so all the assets, capabilities and mitigations available to aggregators also apply to the leader."

For a given _Measurement API_, which is implemented by a client provider, we assume that the client provider will need provide some sets of approved _aggregators_, which are trusted to be non-colluding. By requiring the _leader_ to be an _aggregator_, we limit who can actually be a leader.

Consider a _Measurement API_ implemented by a web browser. In that case, I could imagine both the following scenarios:

1. The site itself wants to act as the leader, collecting the encrypted reports themselves.
2. The site delegates to a service provider, collecting the encrypted reports on that sites behalf (similar to current analytics tools.)

For scenario 1, it seems very unlikely that any site which wishes to act as a _leader_ for themselves would be able to be approved, as that would be a huge undertaking.

For scenario 2, this seems like it would limit competition in this space and potentially give a great deal of benefit to early approved services.

Given this, I propose downgrading the responsibility of the leader to just the storage and coordination role, and not imposing the currently required trust into the _leader_. This would be a fairly significant change to the current draft of the proposal, so before undertaking such changes and providing a PR, I'd like to first what the reaction to this idea is.

**Comment by martinthomson** [comment]
I think that this worth considering.  The current formulation of roles is a little bit biased toward having a single entity that does most of the functions, with a secondary that performs only the necessary additional steps required to avoid collusion.

The current model has:
* a leader that gathers inputs, coordinates aggregation, and assembles the results
* a helper (or helpers) that participate in aggregation

Erik is describing a model where there is a less trusted entity that gathers inputs and assembles results, but does not participate in aggregation.  That entity might coordinate the aggregation process also, though I don't know if that is necessary, depending on what that coordination entails.  If the aggregation functions can talk amongst themselves, that might be more efficient.  Moreover, it might be more trustworthy that way as the (untrusted) coordination function does not need to see intermediate values; in Hits at least, that would leak some information.

Unfortunately, this creates a different set of protocols than what is in the current draft.  You could cut things differently and avoid some (or most) of the complication by allowing this untrusted entity to gather reports and pass them to a leader for aggregation.  That leaves a few unnecessary redundancies in the proposed model.  For instance, you don't need the added complexity of encrypting the output shares toward the collector, because you can rely on TLS instead.

@eriktaubeneck, I think that when you say "storage" you refer only to the phase where individual submissions are gathered prior to running the aggregation protocol.  There is another storage component to this system, which is the anti-replay or budgeting component that ensures that single measurements can't be used too many times.  That part can't be given to an untrusted entity.

**Comment by ekr** [comment]
> Unfortunately, this creates a different set of protocols than what is in the current draft. You could cut things differently and avoid some (or most) of the complication by allowing this untrusted entity to gather reports and pass them to a leader for aggregation. That leaves a few unnecessary redundancies in the proposed model. For instance, you don't need the added complexity of encrypting the output shares toward the collector, because you can rely on TLS instead.

I don't believe that this is correct. The idea here is to avoid any entity other than the collector learning the true value. I don't see how the architectuer Erik proposes would remove that need.

**Comment by martinthomson** [comment]
I understand the goal.  I wanted to maintain that goal.

If you consider an entity that is coordinating and collecting, the shares of the result can be sent to that entity directly rather than using HPKE and routing them via a leader (which at this point is just an unnecessarry intermediary).

**Comment by ekr** [comment]
That puts way more load on that entity than with the current model, so I think this would be a regression.

**Comment by eriktaubeneck** [comment]
There are three different issues being discussed here:

1. What are the properties of the party (currently the leader) who collects the data from the client?
2. What party(s) maintain state for anti-reply and DP budgeting?
3. How are results delivered to the collector so that no other party learns the true value.

I'm primarily proposing a change for 1), as @martinthomson suggests. Thanks for clarifying. Collecting real time data from clients at scale is a non-trivial task, and it seems preferable to have as much flexibility and optionality for eventual collectors who are using this API. Removing the need for trust in the party promotes more competition, and thus more options for pricing, up time, robustness, etc. Dropping data from a client would result in unrecoverable measurement loss (whereas a failed PPM measurement could likely be rerun.)

2) is worth its own issue, though if we are comfortable with a single party managing the longer term state, that could still be compatible with this architecture. The functionality for 1) could be separated out, and called something like "consumer".

For 3), I generally agree with @ekr that minimizing complexity for the aggregators is preferable. Compared to the rest of the protocol, wrapping the result in a HPKE adds a great deal of overhead. In general, it seems ideal to shift as much cost onto the leader (wrt the economics I mention above), and this also plays into egress costs, as described in #130.

**Comment by ekr** [comment]
Erik: I don't understand your point (3).

First, in any situation where one party stores the reports prior to doling them out to the aggregators, they need to be HPKE encrypted, which means that the aggregators need to be able to do HPKE. Any given aggregation will require far more reports than the aggregate value and so wrapping the result in HPKE will be a very small fraction of the HPKEs that the aggregator does. What's the additional overhead here?

Second, I think it's potentially reasonable to introduce *another* entity which orchestrates the computation (as the leader does now), without having the cryptographic keys, but: (1) we certainly want to preserve the ability of a service to offer the same model as now in which the collector issues requests and gets answers without participating in the protocol (2) It's not actually clear to me what the security and privacy properties of this entity would be. At minimum, it seems likely that it would be able to cause the system to produce false results.

**Comment by eriktaubeneck** [comment]
> Erik: I don't understand your point (3).
Ugh, typo. It *doesn't add* a great deal of overhead. I agree it's better to route through the leader, vs having aggregators connect directly to the collector, as @martinthomson suggested.

> (1) we certainly want to preserve the ability of a service to offer the same model as now in which the collector issues requests and gets answers without participating in the protocol
Agreed. In general, I don't see any limits on a single party participating in the protocol in more than role, so long as there are multiple non-colluding parties participating as aggregators.

> (2) It's not actually clear to me what the security and privacy properties of this entity would be. At minimum, it seems likely that it would be able to cause the system to produce false results.
I will take an attempt at describing this in more detail on this issue. My goal would be to design it such that the collector needs to trust this new _consumer_ entity, since they could affect the robustness of the result, but that the clients wouldn't need to trust the _consumer_ because they can't violate the client/end-user privacy.

**Comment by csharrison** [comment]
I just saw this issue from Erik's email on the list. I wanted to point to a similar discussion (https://github.com/abetterinternet/ppm-specification/issues/64) we had a while back on allowing this via considering an intermediary aggregator as another "client" and supporting batch uploads to the leader / aggregators. I think these issues could probably be merged since they are addressing the same underlying goal.

**Comment by eriktaubeneck** [comment]
Thanks for linking @csharrison. Agreed that these seem to be addressing the same underlying goal. #64 is closed, but its outcome is unclear to me. Do you think it's still worth working on achieving this underlying goal?

**Comment by csharrison** [comment]
> Thanks for linking @csharrison. Agreed that these seem to be addressing the same underlying goal. #64 is closed, but its outcome is unclear to me. Do you think it's still worth working on achieving this underlying goal?

The issue isn't closed (just the PR https://github.com/abetterinternet/ppm-specification/pull/78). I still agree on the goal.

cc @cjpatton

**Comment by eriktaubeneck** [comment]
> The issue isn't closed (just the PR #78). I still agree on the goal.
Whoops, misread!

**Comment by cjpatton** [comment]
FWIW, I don't think anyone strongly objects to allowing multiple reports per upload request. This is where we left it previously: https://github.com/abetterinternet/ppm-specification/pull/78#issuecomment-880096898

**Comment by tgeoghegan** [comment]
In the current text, the closest we get to discussing anything like the _consumer_ is [this section](https://github.com/abetterinternet/ppm-specification/blob/main/draft-gpew-priv-ppm.md#anonymizing-proxies-anon-proxy) where we suggest using [OHTTP](https://datatracker.ietf.org/doc/draft-ietf-ohai-ohttp/) to put a server between clients and the aggregators. Besides stripping identifying information like IP addresses, such a server could also do any number of things that are useful in a specific deployment but can't or shouldn't be specified in PPM, like verifying vendor specific attestations from clients to increase confidence that reports are genuine.

As I recall, the goal was to avoid explicitly prescribing how such a server should work in PPM, just to reduce the complexity of the protocol. I still hope OHTTP/OHAI are good answers here, but I also don't think there's anything in the protocol that precludes arbitrary proxy solutions from being deployed. So long as the PPM leader is receiving well-formed reports from the proxy, then the protocol spoken between the proxy and the client can be anything. The exception of course is that the individual reports should be encrypted to the aggregators' HPKE keys by the real clients, but I don't think there's any way for PPM aggregators to prevent a proxy from transcrypting reports.

Anyway, my opinion here is that we should formalize the notion of allowing multiple reports per upload requests to allow efficient batching of reports in client proxies and that we should discuss and illustrate but perhaps not specify how client proxies would be involved in PPM.

**Comment by cjpatton** [comment]
+1 to @tgeoghegan, with one caveat: It may be useful for aggregators to do some sort of attestation of the clients, potentially even through an ingestor proxy. (See https://github.com/abetterinternet/ppm-specification/issues/89.) But this is out-of-scope of the core protocol right now. We included "upload extensions" with the report in order to enable this (see section {{upload-extensions}}), which may or may not be sufficient.

**Comment by cjpatton** [comment]
@eriktaubeneck given the recent discussion on the list, I'm wondering if it's possible to close this and open an issue for tracking the various deployment scenarios folks are considering. Besides that, is there anything else still unresolved in this thread?

**Comment by eriktaubeneck** [comment]
@cjpatton that sounds like a good plan to me. I will close this now and open up a new thread next week.
