### ISSUE TITLE
Allow batch "replay" as required by the PDA protocol (was "Inter-batch replay prevention")

### ISSUE THREAD

**Issue by chris-wood** [abetterinternet/ppm-specification#82]
Similar to #81, it should not be possible for a share to be included in more than one batch. The timestamp currently gives us some way of ensuring that reports map to at most batch, but not a way of ensuring that reports aren't included two _overlapping_ batch windows. It's not immediately clear if include a single report in two overlapping batch windows is a problem, or if a problem only arises when these windows are disjoint. We should probably clarify what are the inter-batch requirements here and what sort of replay prevention is required.

**Comment by cjpatton** [comment]
The aggregators (either the leader or helper) can prevent the collector from getting outputs from overlapping batches by remembering batch intervals. For example, suppose the leader responded successfully to a collect request for time interval `[t0, t1)`. Then suppose that, some time later, the collector requests output shares for `[t0, t2)`, where `t0 < t1 < t2`. The potential privacy violation occurs because the sets of reports in each batch are non-disjoint. To prevent this, the leader might respond to the second request with an error, or it might just include the reports in `[t1, t2)`.

**Comment by tgeoghegan** [comment]
If aggregators are meant to use the report timestamp to protect against replay, then I think it needs to appear in the AEAD-ed message constructed by the client (i.e. `PAEncryptedInputShare`). Otherwise a leader could insert arbitrary timestamps into `PAAggregateSubReq.time` and trick helpers into exceeding privacy budgets or double counting inputs.

**Comment by cjpatton** [comment]
I created a PR that addresses this issue partially. What's left to do is allow multiple collect requests over the same batch, *as required by the PDA protocol* (e.g., Hits). I have an idea for how to do this, I'll follow up with a PR.

**Comment by cjpatton** [comment]
Closed by https://github.com/abetterinternet/ppm-specification/pull/137.
